<a href="https://colab.research.google.com/github/rahuldevkar5/Data_Analyst/blob/main/Python_Basic_Programs_Ans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write Python Programs to use various operators in Python

In [13]:
x = 10
y = 20
print (x+y)

30


In [14]:
x = 10
y = 20
print (x-y)

-10


In [15]:
x = 10
y = 20
print (x*y)

200


In [16]:
x = 10
y = 20
print (x/y)

0.5


In [17]:
x = 100
y = 20
print (x%y)

0


In [18]:
x = 100
y = 20
print (x//y)

5


In [19]:
x = 2
y = 20
print (x**y)

1048576


2. Create list of elements and slice and dice it

In [20]:
List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("\nOriginal List:\n", List)
print("\nSliced Lists: ")
print(List[3:9:2])
print(List[::2])
print(List[::])



Original List:
 [1, 2, 3, 4, 5, 6, 7, 8, 9]

Sliced Lists: 
[4, 6, 8]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [21]:
import random
def dice():
    n = input( "Enter # of dice [3,6]: " )
    n = int( n )
    diceList = []
    for row in range(0, n):
        diceList.append(random.randint(1, 6))
    print( "\nYou have rolled: ", diceList)
dice()

Enter # of dice [3,6]: 4

You have rolled:  [6, 2, 5, 6]


3. Using while loop accept numbers until sum of numbers is less than 100

In [24]:
total_sum = 0
a = int(input())
while a != 0:
    total_sum += a
    if total_sum >= 100:
        print('Total sum is', total_sum)
        break
    a = int(input())
else:
    print('Total sum is less than 100 and is equal to', total_sum, '.')

23
45
43
Total sum is 111


4. Write a python program Read & write Excel files 

In [26]:
import pandas as pd
info = pd.DataFrame({'States':['California', 'Florida', 'Montana', 'Colorodo', 'Washington', 'Virginia'],
    'Capitals':['Sacramento', 'Tallahassee', 'Helena', 'Denver', 'Olympia', 'Richmond'],
    'Population':['508529', '193551', '32315', '619968', '52555', '227032']})

In [28]:
# writing excel file
info.to_excel('./info.xlsx')

In [30]:
info.to_excel('./info.xlsx', sheet_name='info', index=False)

In [31]:
# raeding excel file
students_grades = pd.read_excel('/content/Weekly report - ExcelR - Main.xlsx')
students_grades.head()

Incident ID Company  ... Time Spent           TTR
0  N-IM032663567     AIM  ...   8.478044  12208.383333
1  N-IM032686983     AIM  ...   6.006562   8649.450000
2  N-IM032749875     AIM  ...   1.851308   2665.883333
3  N-IM032788281     AIM  ...   0.215660    310.550000
4  N-IM032798013     AIM  ...   0.001956      2.816667

[5 rows x 10 columns]

5. Write a python program to scrape reviews from a commercial web site


In [46]:
from bs4 import BeautifulSoup
import urllib.request

In [47]:
url = 'https://www.yelp.com/biz/milk-and-cream-cereal-bar-new-york?osq=Ice+Cream'
ourUrl = urllib.request.urlopen(url)

In [48]:
soup = BeautifulSoup(ourUrl,'html.parser')

In [49]:
print(soup.prettify())

<!DOCTYPE HTML>
<!--[if lt IE 7 ]> <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie6 ie ltie9 ltie8 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie7 ie ltie9 ltie8 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie8 ie ltie9 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie9 ie no-js" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en" xmlns:fb="http://www.facebook.com/2008/fbml">
 <!--<![endif]-->
 <head>
  <script nonce="085631e4">
   (function() {
                var main = null;

                var main=function(){window.onerror=function(k,a,c,i,f){var j=(document.getElementsByTagName("html")[0].getAttribute("webdriver")==="true"||navigator.userAgent==="selenium");var h=f&&(f.name==="ServerSideRenderingError"||f.name==="CSRFallbackError");if(j&&!h){documen

In [52]:
review = []
for i in soup.find_all('div',{'class':'review-content'}):
  per_review=i.find('p')
  print(per_review)
  review.append(per_review)

In [ ]:
len(review)

6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [54]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


7.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [56]:
import numpy as np
l = [1,2,3,4]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [1, 2, 3, 4]
One-dimensional NumPy array:  [1 2 3 4]


8.Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [57]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
